version: "3"
services:
  dbpostgres:
    build: ./postgres
    image: private:5000/db-postgres
    restart: always
    volumes:
      - vol-dbpostgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
     POSTGRES_USER: tpi2018
     POSTGRES_PASSWORD: tpipass
     POSTGRES_DB: mantenimiento
  web:
    build: ./payara
    image: private:5000/web-payara
    ports:
      - "8082:8080"
    depends_on:
      - dbpostgres
volumes:
  vol-dbpostgres: